version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - PORT=5050
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
